
Spring:
  Datasource:
    Url: jdbc:postgresql://localhost:5432/academia?Timezone=true&serverTimezone=UTC&useLegacyDate
    Username: postgres
    password: lbm320

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  logging:
    level:
      org:
        hibernate:
          type: trace




